import clsx from "clsx";
import { useId } from "react";
import type { TextAreaProps } from "@/components/form/inputs/textArea/textArea.types";
import { Block } from "@/components/primitives";
import FormFieldWrapper from "../../field";

export default function TextArea(
    {
        helper,
        className,
        required,
        label,
        errorMessage,
        id,
        ...props
    }: TextAreaProps) {

    const autogeneratedId = useId();
    const inputId = id ?? autogeneratedId;

    const ariaDescribedByIds = [
        helper ? `${inputId}-helper` : null,
        errorMessage ? `${inputId}-error` : null,
    ]
        .filter(Boolean)
        .join(" ") || undefined;

    return (
        <FormFieldWrapper
            inputId={inputId}
            label={label}
            helper={helper}
            required={required}
            errorMessage={errorMessage}
        >
            <Block
                as="textarea"
                id={inputId}
                aria-invalid={!!errorMessage}
                aria-describedby={ariaDescribedByIds}
                aria-required={required}
                className={clsx("input-group__input text-area", className)}
                required={required}
                {...props}
            />
        </ FormFieldWrapper>
    );
}