import clsx from "clsx";
import { useId } from "react";
import type { TextAreaProps } from "@/components/form/inputs/textArea/textArea.types";
import { RiErrorWarningFill } from "@remixicon/react";
import Icon from "@/components/icon";
import { Block } from "@/components/primitives";

export default function TextArea(
    {
        helper,
        className,
        required,
        label,
        error,
        id,
        ...props
    }: TextAreaProps) {

    const autogeneratedId = useId();
    const inputId = id ?? autogeneratedId;

    const ariaDescribedByIds = [
        helper ? `${inputId}-helper` : null,
        error ? `${inputId}-error` : null,
    ]
        .filter(Boolean)
        .join(" ") || undefined;

    return (
        <div className="input-group" data-invalid={error ? true : undefined}>
            <label htmlFor={inputId} className="input-group__label">
                {label}
                {required && <span className="input-group__required" aria-hidden="true">*</span>}
            </label>
            {helper && (
                <p id={`${inputId}-helper`} className="input-group__helper text-sm">
                    {helper}
                </p>
            )}
            {error && (
                <p id={`${inputId}-error`} className="input-group__error">
                    <Icon icon={RiErrorWarningFill} /> {error}
                </p>
            )}
            <Block
                as="textarea"
                id={inputId}
                aria-invalid={!!error}
                aria-describedby={ariaDescribedByIds}
                aria-required={required}
                className={clsx("input-group__input", className)}
                required={required}
                {...props}
            />
        </div>
    );
}