import clsx from "clsx";
import { useId } from "react";
import type { TextInputProps } from "@/components/form/inputs/textInput/textInput.types";
import { Block } from "@/components/primitives";
import FormFieldWrapper from "@/components/form/field";

export default function TextInput(
    {
        helper,
        label,
        errorMessage,
        className,
        required,
        id,
        ...props
    }: TextInputProps) {

    const autogeneratedId = useId();
    const inputId = id ?? autogeneratedId;

    const ariaDescribedByIds = [
        helper ? `${inputId}-helper` : null,
        errorMessage ? `${inputId}-error` : null,
    ]
        .filter(Boolean)
        .join(" ") || undefined;

    return (

        <FormFieldWrapper
            inputId={inputId}
            label={label}
            helper={helper}
            required={required}
            errorMessage={errorMessage}
        >
            <Block
                as="input"
                id={inputId}
                aria-invalid={!!errorMessage}
                aria-describedby={ariaDescribedByIds}
                aria-required={required}
                className={clsx("input-group__input text-input", className)}
                required={required}
                {...props}
            />
        </FormFieldWrapper>

    );
}