'use client';
import { useFocusTrap } from '@/hooks/useFocusTrap';
import { usePathname } from 'next/navigation';
import { useEffect, useId, useRef, useState } from 'react'
import { useClickOutside } from '@/hooks/useClickOutside';
import { useMediaQuery } from '@/hooks/useMediaQuery';
import type { HamburgerState, useHamburgerProps } from '@/components/hamburger/hamburger.types';

export default function useHamburger({
  id,
  position = "left",
  breakpoint = "mobile",
  wrapperRef
  }: useHamburgerProps) {
  const [menuState, setMenuState] = useState<HamburgerState['menuState']>("inactive");
  const { isMobile, isTablet, mounted } = useMediaQuery();

  const isActive = (() => {
    if (!mounted) return false;
    if (breakpoint === 'mobile') return isMobile;
    if (breakpoint === 'tablet') return isMobile || isTablet;
    return true; // 'desktop' means always active
  })();

  const pathname = usePathname()
  const autogeneratedId = useId();
  const menuId = id ?? autogeneratedId;

  const menuRef = useRef<HTMLElement | null>(null);
  const buttonRef = useRef<HTMLButtonElement | null>(null);
  useClickOutside(
    () => {
      if (isActive) {
        toggleMenuOpenState();
        buttonRef.current?.focus();
      }
    },
    wrapperRef,
    menuState === "open" && isActive
  );

  function closeMenu() {
    setMenuState("inactive")
  }

  function toggleMenuOpenState() {
    setMenuState(prev => prev === "open" ? "closed" : "open");
  }

  useFocusTrap({
    containerRef: wrapperRef,
    isActive: Boolean(menuState === "open" && isActive),
  });

  // close when switching to desktop
  useEffect(() => {
    if (!isActive && menuState !== "inactive") {
      closeMenu();
    }
  }, [isActive, menuState]);

  // close when pathname changes
  useEffect(() => {
    if (isActive && menuState !== "inactive") {
      closeMenu();
    }
  }, [pathname])

  // Close on Escape key
  useEffect(() => {
    if (menuState !== "open" || !isActive) return;

    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        toggleMenuOpenState();
        buttonRef.current?.focus();
      }
    };

    document.addEventListener("keydown", handleKey);
    return () => document.removeEventListener("keydown", handleKey);
  }, [menuState, isActive]);

  return {
    isActive,
    menuState,
    toggleMenuOpenState,
    menuId,
    menuRef,
    buttonRef,
    position
  };
}
