'use client';
import { useFocusTrap } from '@/hooks/useFocusTrap';
import { usePathname } from 'next/navigation';
import { useEffect, useId, useRef, useState } from 'react'
import { useClickOutside } from '@/hooks/useClickOutside';
import { useMediaQuery } from '@/hooks/useMediaQuery';
import type { HamburgerState } from '@/components/hamburger/hamburger.types';

export default function useHamburger(
  id?: HamburgerState["menuId"],
  position: HamburgerState["position"] = "left",
  breakpoint: HamburgerState["breakpoint"] = "mobile"
): HamburgerState {
  const [menuIsOpen, setMenuIsOpen] = useState<HamburgerState['menuIsOpen']>(undefined);
  const { isMobile, isTablet } = useMediaQuery();

  const isActive = 
    breakpoint === 'mobile' ? isMobile :
    breakpoint === 'tablet' ? (isMobile || isTablet) :
    true; // 'desktop' means always active

  const pathname = usePathname()
  const autogeneratedId = useId();
  const menuId = id ?? autogeneratedId;

  const menuRef = useRef<HTMLElement | null>(null);
  const buttonRef = useRef<HTMLButtonElement | null>(null);
  const wrapperRef = useClickOutside<HTMLDivElement>(
    null,
    () => isActive ? toggleMenuOpenState(false) : null,
    menuIsOpen === true && isActive
  );

  function toggleMenuOpenState(state?: boolean) {
    setMenuIsOpen(prev => state ?? !prev);
  }

  useFocusTrap({
    containerRef: menuRef,
    isActive: Boolean(menuIsOpen && isActive),
  });

  // close when switching to desktop
  useEffect(() => {
    if (!isActive && menuIsOpen) {
      toggleMenuOpenState(undefined);
    }
  }, [isActive]);

  // close when pathname changes
  useEffect(() => {
    if (isActive && menuIsOpen) {
      toggleMenuOpenState(false);
    }
  }, [pathname])

  // Close on Escape key
  useEffect(() => {
    if (!menuIsOpen || !isActive) return;

    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        toggleMenuOpenState(false);
        buttonRef.current?.focus();
      }
    };

    document.addEventListener("keydown", handleKey);
    return () => document.removeEventListener("keydown", handleKey);
  }, [menuIsOpen, isActive]);

  return {
    isActive,
    menuIsOpen,
    toggleMenuOpenState,
    menuId,
    menuRef,
    buttonRef,
    wrapperRef,
    position
  };
}
